### ISSUE TITLE
[Feature Request] Upgrade Jinja2 compatibility

### ISSUE THREAD

**Issue by tai271828** [pycontw/postevent-report-generator#55]
## Description
We are still using Jinja2 v6.x, and the API of Jinjga2 in the later versions.

## Possible Solution
Update the API of Jinja2 we are currently using.

## Related Issue
If applicable, add link to existing issue also help us know better.
https://github.com/pycontw/postevent-report-generator/pull/53#discussion_r889497081

**Comment by tai271828** [comment]
I think we should pin the version of markupsafe used by jinja2 as well.

```
(rg-cli-pip-sandbox2-kYDtoQuq-py3.9) [^_^]─[~/work-my-projects/pycontw-projects/post-events/data-for-dev] tai271828@syakaro: 220613-15:16:42 9 file 112Kb
$ rg-cli --talks-csv ./talks-list.csv --proposed-talks-csv ./talks-list-proposed.csv --booth-csv ./booth.csv --csv ./reserved-attendees-2020.csv --csv ./individual-attendees-2020.csv --csv ./corporate-attendees-2020.csv --yaml ./general-
plots-en.yaml --package-yaml ./packages.yaml --sponsor-yaml ./sponsors.yaml     
Traceback (most recent call last):                                                                                                                       
  File "/home/tai271828/.cache/pypoetry/virtualenvs/rg-cli-pip-sandbox2-kYDtoQuq-py3.9/bin/rg-cli", line 5, in <module>
    from report_generator.controller.report_generator_cli import main
  File "/home/tai271828/.cache/pypoetry/virtualenvs/rg-cli-pip-sandbox2-kYDtoQuq-py3.9/lib/python3.9/site-packages/report_generator/controller/report_generator_cli.py", line 10, in <module>
    import report_generator.exporter.html as exporter_html
  File "/home/tai271828/.cache/pypoetry/virtualenvs/rg-cli-pip-sandbox2-kYDtoQuq-py3.9/lib/python3.9/site-packages/report_generator/exporter/html.py", line 5, in <module>
    from jinja2 import BaseLoader, Environment, Markup, PackageLoader                                                  
  File "/home/tai271828/.cache/pypoetry/virtualenvs/rg-cli-pip-sandbox2-kYDtoQuq-py3.9/lib/python3.9/site-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template                                                                     
  File "/home/tai271828/.cache/pypoetry/virtualenvs/rg-cli-pip-sandbox2-kYDtoQuq-py3.9/lib/python3.9/site-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes                                                                                          
  File "/home/tai271828/.cache/pypoetry/virtualenvs/rg-cli-pip-sandbox2-kYDtoQuq-py3.9/lib/python3.9/site-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup                                                                                          
  File "/home/tai271828/.cache/pypoetry/virtualenvs/rg-cli-pip-sandbox2-kYDtoQuq-py3.9/lib/python3.9/site-packages/jinja2/utils.py", line 642, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/tai271828/.cache/pypoetry/virtualenvs/rg-cli-pip-sandbox2-kYDtoQuq-py3.9/lib/python3.9/site-packages/markupsafe/__init__.py)
```
